#include<iostream>
using namespace std;
class Musobaqa{
    public:
        static int yil;
        string jamoa;
        int achko;
    void setKirit(){
         cout << "musobaqa tashkil qilingan yil"; cin >> yil;
         cout << "jamoa"; cin >> jamoa;
         cout << "achko"; cin >> achko;
    }    
    void getChiqar(){
         cout << yil << " " << jamoa << " " << achko ;
    }


// davomi bor










};
















